# Generated by Django 4.0.3 on 2022-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rain', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('update_time', models.CharField(max_length=50)),
                ('weather_time', models.CharField(max_length=20)),
                ('hour', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'avenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='esp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('weather_time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'esp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='interia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rain', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('update_time', models.CharField(max_length=50)),
                ('weather_time', models.CharField(max_length=20)),
                ('hour', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'interia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'mails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='metroprog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rain', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('update_time', models.CharField(max_length=50)),
                ('weather_time', models.CharField(max_length=20)),
                ('hour', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'metroprog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='onet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rain', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('update_time', models.CharField(max_length=50)),
                ('weather_time', models.CharField(max_length=20)),
                ('hour', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'onet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='weatherChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rain', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('update_time', models.CharField(max_length=50)),
                ('weather_time', models.CharField(max_length=20)),
                ('hour', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'weatherChannel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='wp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rain', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('update_time', models.CharField(max_length=50)),
                ('weather_time', models.CharField(max_length=20)),
                ('hour', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'wp',
                'managed': False,
            },
        ),
    ]
