# Generated by Django 4.0.3 on 2022-04-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interia',
            table='interia',
        ),
    ]
