# Generated by Django 4.0.3 on 2022-04-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_interia_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='avenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rain', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('update_time', models.CharField(max_length=50)),
                ('weather_time', models.CharField(max_length=20)),
                ('hour', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'avenue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='weatherChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('rain', models.FloatField()),
                ('cloudiness', models.IntegerField()),
                ('update_time', models.CharField(max_length=50)),
                ('weather_time', models.CharField(max_length=20)),
                ('hour', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'weatherChannel',
                'managed': False,
            },
        ),
    ]
